#ifndef __SCRIPTDEF_H__
#define __SCRIPTDEF_H__

#define SW_START 0
#define SW_PIC1FADE 1
#define SW_VEC1 2
#define SW_KASW 3
#define SW_CYLT 4
#define SW_PART 5
#define SW_PICTURE2 6
#define SW_PIC2FADE0 7
#define SW_PIC2FADE1 8
#define SW_SCRO 9
#define SW_BLANK 10
#define SW_S_B1 11
#define SW_S_B2 12
#define SW_PULS 13
#define SW_WIRE 14
#define SW_BLOB 15
#define SW_SPIC1 16
#define SW_SPOL 17
#define SW_CREDON 18
#define SW_VECSPD 22
#define SW_VECACC 23
#define SW_CREDVAL 24
#define SW_CREDEND 25
#define SW_CREDSPD 26
#define SW_KASWFADEVAL 27
#define SW_KASWFADEEND 28
#define SW_KASWFADESPD 29
#define SW_VECFADEVAL 30
#define SW_VECFADEEND 31
#define SW_VECFADESPD 32
#define SW_CYLOFFSET 33
#define SW_WEKNOWS 34
#define SW_BLOBRADIAL 35
#define SW_BLOBFADEVAL 36
#define SW_BLOBFADEEND 37
#define SW_BLOBFADESPD 38
#define SW_CYLFADEVAL 39
#define SW_WIREZOOM 40
#define SW_WIREROTX 41
#define SW_WIREROTY 42
#define SW_WIREROTZ 43
#define SW_KASWFLASHCOL 44
#define SW_OK 45
#define SW_OKFADEVAL 46
#define SW_OKFADEEND 47
#define SW_OKFADESPD 48
#define SW_OKFADECOL 49
#define SW_KASWR 50
#define SW_KASWG 51
#define SW_KASWB 52
#define SW_META 53
#define SW_METASPD 54
#define SW_METAUD 55
#define SW_METAFADEVAL 56
#define SW_METAFADEEND 57
#define SW_METAFADESPD 58
#define SW_BLOBGFX 59


#endif
